apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cd-mvn-build
spec:
  steps:
    - name: mvn-build-jar
      image: maven:eclipse-temurin-17
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        mvn package -DskipTests
