apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout-clone
spec:
  params:
    - name: repo-url
      description: The git repository url
      type: string

    - name: branch
      description: The branch to be cloned
      type: string

  steps:
    - name: clone-repo
      image: alpine/git
      script: | 
       #!/bin/sh
       echo "cloning repository with $(params.branch) branch and repo $(params.repo-url)"
       git clone -b $(params.branch) $(params.repo-url) workspace/source
       echo "clone completed"
       echo "current working directory"
       pwd
       echo " changing to home dir"
       cd /
       echo "ls cd /"
       echo "cd workspace"
       cd workspace
       echo "ls workspace"
       ls 
        
