apiVersion: tekton.dev/v1beta1
kind: Tasks
metadata:
  name: cd-docker-image
spec:
  params:
     - name: image-url
       description: dockerhub image url
       type: string

  steps:
    - name: build-and-push
      image: docker
      workingDir: /workspace/source
      script: |
        #!/bin/sh
        docker build -t $(params.image-url):latest .
        docker push $(params.image-url):latest