apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-pcas
  namespace: pcas
rules:
  - apiGroups: [""]
    resources: [ "pods","services","configmaps","secrets" ]
    verbs: [ "get","list","create","delete","update" ]
  - apiGroups: [ "tekton.dev" ]
    resources: [ "pipelineruns","pipelines","tasks" ]
    verbs: [ "get","list","create","delete","update" ]