apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: product-catalog-ci-cd-pipeline
spec:
  params:
    - name: repo-url
    - name: branch

  tasks:
    - name: clone
      taskRef:
        name: checkout-clone
      params:
        - name: repo-url
          value: "$(params.repo-url)"
        - name: branch
          value: "$(params.branch)"

    - name: echo
      taskRef:
        name: echo-workspace
      runAfter:
        - clone

    - name: tests
      taskRef:
        name: cd-mvn-test
      runAfter:
        - echo

    - name: build
      taskRef:
        name: cd-mvn-build
      runAfter:
        - tests


#            have to do a lot of work
#             i need to do actual implementation of the steps below
#     steps to be followed below
#   1. ✅ Linting → Using checkstyle or spotbugs for static analysis
#   2. ✅ Testing → Running JUnit tests with Maven
#   3. ✅ Building → Creating a JAR file with Maven
#   4. ✅ Docker Image Build → Building a container image using Docker
#   5. ✅ Deployment → Deploying to a Kubernetes cluster