apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline-message
spec:
  params:
    - name: message
  tasks:
    - name: hello
      taskRef:
        name: echomessage
      params:
        - name: message
          value: "$(params.message)"