apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pcas-role-binding
  namespace: pcas
subjects:
  - kind: ServiceAccount
    name: pcas-sa
    namespace: pcas
roleRef:
  kind: Role
  name: pcas-role
  apiGroup: rbac.authorization.k8s.io